### ISSUE TITLE
Consider an order for selectors in CSS

### ISSUE THREAD

**Issue by h3xar0n** [Hickman87/prj-rev-bwfs-dasmoto#4]
This is purely optional, but on larger projects, it will be an essential organizational trait: try to pick an order for selectors in CSS that is immediately clear to readers.

If you move from general element selectors (`h1`, `h2`) to class selectors (`.header-image`), then revert back and forth, it can be difficult to reason about. In your case, the project is very small, and it's clear that you're listing selectors in the order that they appear in the flow. On larger projects, it may help to include CSS comments that indicate the section, e.g.

```css
/* Top banner */
h1 {
  font-size: 50px;
}
.banner {
  background-color: blue;
}

/* All sections */
h2 {
  font-size: 20px;
}
section {
  padding: 50px;
}

/* Car section */
section.car h2 {
  color: blue;
}
```

Here are some good tips on various approaches:

https://meiert.com/en/blog/how-to-order-css-selectors/
